### ISSUE TITLE
Why is class pitchModel defined differently in the file pitch_inference.py and the file pitch_attention_adv.py?

### ISSUE THREAD

**Issue by wosyoo** [iiscleap/ZEST#7]
in the file pitch_inference.py, self.speaker_linear = nn.Linear(192, 128)
but in the file pitch_inference.py, self.speaker_linear = nn.Linear(128, 128)
I used torch.save(model.state_dict(), 'f0_predictor.pth') because torch.save(model,'f0_predictor.pth') reported an error when I loaded the trained model with the following statement:
model = PitchModel(hparams) model.load_state_dict(torch.load('f0_predictor.pth', map_location=device))
This is because the definitions of the two pitchModel classes do not agree.

**Comment by Soumya-dutta** [comment]
Yeah. It was a mistake. It will be nn.Linear(128, 128)The 192 was because I was also experimenting with the original x-vectors (which have a dimension of 192) in one of the ablation experiments. If you are using EASE vectors for speaker embedding, you should always use 128 as the input dimension.

I have corrected the code.

Thanks for pointing this out.
